version: '3'

services:
  api:
    container_name: app_api_rest_evaluation_alm_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    working_dir: /usr/src/app
    networks:
      - app-network
    links:
      - mongodb

  mongodb:
    image: mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
